/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddLive: typeof import('./components/AddLive.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Creator: typeof import('./components/Creator.vue')['default']
    CreatorPage: typeof import('./components/CreatorPage.vue')['default']
    EventsPage: typeof import('./components/EventsPage.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HomePage: typeof import('./components/HomePage.vue')['default']
    LiveForm: typeof import('./components/LiveForm.vue')['default']
    LiveList: typeof import('./components/LiveList.vue')['default']
    LivePage: typeof import('./components/LivePage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserList: typeof import('./components/UserList.vue')['default']
  }
}
